# Generated by Django 2.1.5 on 2019-08-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='germ_date',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='grow_date',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='harvest_date',
        ),
        migrations.AlterField(
            model_name='croprecord',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_records', to='inventory.Crop'),
        ),
    ]
