# Generated by Django 2.1.5 on 2019-09-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190827_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inhouse',
            old_name='num_small',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='weekdayrequirement',
            old_name='num_small',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='inhouse',
            name='num_big',
        ),
        migrations.RemoveField(
            model_name='inhouse',
            name='num_medium',
        ),
        migrations.RemoveField(
            model_name='weekdayrequirement',
            name='num_big',
        ),
        migrations.RemoveField(
            model_name='weekdayrequirement',
            name='num_medium',
        ),
    ]
