# Generated by Django 2.1.5 on 2019-04-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190419_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='days_plant_to_harvest',
        ),
        migrations.AddField(
            model_name='variety',
            name='days_germ',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='variety',
            name='days_grow',
            field=models.IntegerField(null=True),
        ),
    ]
