# Generated by Django 2.1.5 on 2019-07-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190724_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='seeding_density',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
