# Generated by Django 2.1.5 on 2019-09-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_killreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryaction',
            name='kill_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.KillReason'),
        ),
    ]
