# Generated by Django 2.1.5 on 2019-07-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_crop_seeding_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
