# Generated by Django 2.1.5 on 2019-09-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryaction_kill_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('seed_date', models.DateField()),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Variety')),
            ],
        ),
        migrations.RemoveField(
            model_name='inhouse',
            name='variety',
        ),
        migrations.DeleteModel(
            name='InHouse',
        ),
    ]
