# Generated by Django 2.1.5 on 2019-09-03 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryaction_kill_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropGroup',
            fields=[
                ('variety', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='inventory.Variety')),
                ('quantity', models.IntegerField(default=0)),
                ('seed_date', models.DateField()),
            ],
        ),
    ]
