# Generated by Django 2.1.5 on 2019-08-15 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190725_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='germ_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='crop',
            name='grow_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
