# Generated by Django 2.1.5 on 2019-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190906_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryaction',
            name='kill_reason',
        ),
        migrations.AddField(
            model_name='inventoryaction',
            name='kill_reasons',
            field=models.ManyToManyField(null=True, to='inventory.KillReason'),
        ),
    ]
