# Generated by Django 2.1.5 on 2019-09-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20190918_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryaction',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
