# Generated by Django 2.1.5 on 2019-10-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20191001_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='lead_time',
            field=models.IntegerField(null=True),
        ),
    ]
