# Generated by Django 2.1.5 on 2019-10-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_variety_lead_time'),
    ]

    database_operations = [
        migrations.AlterModelTable('CropAttribute', 'golden_trays_cropattribute'),
        migrations.AlterModelTable('CropAttributeOption', 'golden_trays_cropattributeoption'),
        migrations.AlterModelTable('Crop', 'golden_trays_crop'),
        migrations.AlterModelTable('CropRecord', 'golden_trays_croprecord'),
        migrations.AlterModelTable('Slot', 'golden_trays_slot'),
    ]

    state_operations = [
        migrations.DeleteModel('CropAttribute'),
        migrations.DeleteModel('CropAttributeOption'),
        migrations.DeleteModel('Crop'),
        migrations.DeleteModel('CropRecord'),
        migrations.DeleteModel('Slot'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]

    atomic = False
