# Generated by Django 2.1.5 on 2019-10-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_variety_lead_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Variety'),
        ),
    ]
