# Generated by Django 2.1.5 on 2019-10-17 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20191014_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryaction',
            name='harvest_yield',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='variety',
            name='alph_num_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='weekdayrequirement',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Variety'),
        ),
    ]
