# Generated by Django 2.1.5 on 2019-10-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20191014_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='alph_num_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
