# Generated by Django 2.1.5 on 2019-10-15 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_variety_alph_num_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdayrequirement',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Variety'),
        ),
    ]
