# Generated by Django 2.1.5 on 2019-10-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20191015_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryaction',
            name='variety',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Variety'),
        ),
    ]
