# Generated by Django 2.1.5 on 2019-10-14 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0011_auto_20191014_1242'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_yield', models.FloatField(blank=True, null=True)),
                ('leaf_wingspan', models.FloatField(blank=True, null=True)),
                ('seeding_density', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'golden_trays_crop',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CropAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'golden_trays_cropattribute',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CropAttributeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='golden_trays.CropAttribute')),
            ],
            options={
                'db_table': 'golden_trays_cropattributeoption',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CropRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('record_type', models.CharField(choices=[('GERM', 'Started Germination Phase'), ('GROW', 'Started Grow Phase'), ('WATER', 'Watered'), ('HARVEST', 'Harvested'), ('TRASH', 'Trashed')], max_length=10)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_records', to='golden_trays.Crop')),
            ],
            options={
                'db_table': 'golden_trays_croprecord',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=50, unique=True)),
                ('current_crop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_slot', to='golden_trays.Crop')),
            ],
            options={
                'db_table': 'golden_trays_Slot',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='crop',
            name='attributes',
            field=models.ManyToManyField(related_name='crops', to='golden_trays.cropattributeoption'),
        ),
        migrations.AddField(
            model_name='crop',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Variety'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
