# Generated by Django 2.1.5 on 2019-10-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golden_trays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crop',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cropattribute',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cropattributeoption',
            table=None,
        ),
        migrations.AlterModelTable(
            name='croprecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='slot',
            table=None,
        ),
    ]
    atomic = False
