# Generated by Django 2.1.5 on 2019-10-18 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golden_trays', '0002_auto_20191015_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Variety'),
        ),
    ]
