# Generated by Django 2.1.5 on 2019-10-18 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golden_trays', '0003_auto_20191018_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='current_crop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_slot', to='golden_trays.Crop'),
        ),
    ]
