# Generated by Django 2.1.5 on 2019-09-30 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0008_inventoryaction_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestedCropProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Product')),
                ('size', models.CharField(choices=[(0, 'SMALL'), (1, 'LARGE')], max_length=40)),
                ('weight', models.FloatField()),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Variety')),
            ],
            bases=('orders.product',),
        ),
        migrations.CreateModel(
            name='LiveCropProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Product')),
                ('size', models.CharField(choices=[(0, 'SMALL'), (1, 'LARGE')], max_length=40)),
                ('tray_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.TrayType')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Variety')),
            ],
            bases=('orders.product',),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Product'),
        ),
    ]
