# Generated by Django 2.1.5 on 2019-10-15 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='alph_num_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='harvestedcropproduct',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvested_crop_products', to='inventory.Variety'),
        ),
        migrations.AlterField(
            model_name='livecropproduct',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_crop_products', to='inventory.Variety'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='products', to='orders.Tag'),
        ),
    ]
