# Generated by Django 2.1.5 on 2019-10-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191015_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='black', max_length=25),
        ),
    ]
