# Generated by Django 2.1.5 on 2019-10-17 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
